site_name: Paliak's Notes
base_url: /PaliaksNotes
theme:
  name: null
  custom_dir: 'custom_theme/'
  darkmode: true
  highlightjs: true
  hljs_languages:
    - powershell
plugins: []

repo_url: "https://github.com/Paliak"
